filebeat.inputs:
- type: log
  enabled: true
  paths:
    - PATHS
  multiline.pattern: ^\[
  multiline.negate: true
  multiline.match: after
setup.template.settings:
  index.number_of_shards: 1
setup.kibana:
  host: "KI_SERVER"
output.elasticsearch:
  hosts: ["ES_SERVER"]
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
